name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # ✅ Build Docker Image (Lowercase Repository Owner)
      - name: Build Docker Image
        run: docker build -t ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/fiscochat:latest .

      # ✅ Tag Docker Image (Lowercase Repository Owner)
      - name: Tag Docker Image
        run: |
          docker tag ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/fiscochat:latest ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/fiscochat:${{ github.sha }}

      # ✅ Push Docker Image (Lowercase Repository Owner)
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/fiscochat:latest
          docker push ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/fiscochat:${{ github.sha }}
