name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Print GitHub Repository Name
      - name: Debug - Print Repository
        run: |
          echo "Repository: ${{ github.repository }}"

      # Build Docker Image Using Organization Name
      - name: Build Docker Image
        run: docker build -t ghcr.io/fizcochat/${GITHUB_REPOSITORY#*/}:latest .

      # Tag Docker Image with Commit SHA
      - name: Tag Docker Image
        run: |
          docker tag ghcr.io/fizcochat/${GITHUB_REPOSITORY#*/}:latest ghcr.io/fizcochat/${GITHUB_REPOSITORY#*/}:${{ github.sha }}

      # Push Docker Image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/fizcochat/${GITHUB_REPOSITORY#*/}:latest
          docker push ghcr.io/fizcochat/${GITHUB_REPOSITORY#*/}:${{ github.sha }}
