name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # ✅ Set Repository Name Lowercase and Replace Underscores with Dashes (GitHub Actions Syntax)
      - name: Set Repository Name Lowercase
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g' >> $GITHUB_ENV

      # ✅ Debug - Print REPO_NAME
      - name: Debug - Print REPO_NAME
        run: |
          echo "Repository Name in Lowercase: ${{ env.REPO_NAME }}"

      # ✅ Build Docker Image
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest .

      # ✅ Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.sha }}

      # ✅ Push Docker Image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.sha }}
