name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set Repository Name Lowercase
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest .

      - name: Tag Docker Image
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.sha }}