name: Python tests

on:
  push:
    branches: [ main, bert ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create dummy model directory
      run: |
        mkdir -p bert/models/enhanced_bert
        touch bert/models/enhanced_bert/config.json
        
    - name: Run tests
      env:
        PYTEST_CURRENT_TEST: "yes"  # Signal test environment
        OPENAI_API_KEY: "sk-dummy-key-for-testing"
        PINECONE_API_KEY: "dummy-pinecone-key-for-testing"
      run: |
        pytest tests/ --cov=./ --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 