name: Python Tests

on:
  push:
    branches: [ main, dockerV2 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov flake8
    
    - name: Set environment variables
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      run: echo "Environment variables OPENAI_API_KEY and PINECONE_API_KEY are set"

    - name: Run tests with coverage
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      run: |
        pytest --cov=./ --cov-report=xml
    
    - name: Build Docker image
      run: |
        docker build -t rag-chatbot .
        docker run -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                   -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
                   rag-chatbot pytest
