name: Python Tests

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install the package in editable mode
        pip install -e .
    
    - name: Set environment variables
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      run: |
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV
        echo "PINECONE_API_KEY=$PINECONE_API_KEY" >> $GITHUB_ENV

    - name: Run tests with coverage
      run: |
        # Create test data directories if they don't exist
        mkdir -p fast_text/models
        mkdir -p data_documents
        mkdir -p dtaa-documents
        mkdir -p argilla_data_49
        mkdir -p argilla-data
        
        # Create a dummy model file for testing
        echo "dummy model" > fast_text/models/tax_classifier.bin
        
        # List test files for debugging
        echo "Test files found:"
        find . -name "test_*.py" -o -name "*_test.py"
        
        # Run tests with coverage and detailed output
        python -m pytest \
          --verbose \
          --cov=fast_text \
          --cov-report=xml \
          --cov-report=term-missing \
          -v fast_text/test_relevance.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PYTHONPATH: ${{ github.workspace }}
        PYTEST_ADDOPTS: "--color=yes"

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/fizcochat/${GITHUB_REPOSITORY,,}:latest .

      - name: Run Tests Inside Docker Container
        run: |
          docker run --rm -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                        -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
                        ghcr.io/fizcochat/${GITHUB_REPOSITORY,,}:latest pytest

      - name: Tag Docker Image
        run: |
          docker tag ghcr.io/fizcochat/${GITHUB_REPOSITORY,,}:latest ghcr.io/fizcochat/${GITHUB_REPOSITORY,,}:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/fizcochat/${GITHUB_REPOSITORY,,}:latest
          docker push ghcr.io/fizcochat/${GITHUB_REPOSITORY,,}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      
      - name: Deploy Container
        run: |
          echo "Deploying container..."
          docker pull ghcr.io/fizcochat/${GITHUB_REPOSITORY,,}:latest
          docker stop rag-chatbot || true
          docker rm rag-chatbot || true
          docker run -d --name rag-chatbot -p 8501:8501 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
            ghcr.io/fizcochat/${GITHUB_REPOSITORY,,}:latest