[theme]
primaryColor="#3c4c9c"
backgroundColor="#f8f9fd"
secondaryBackgroundColor="#e8eaf7"
textColor="#333333"
font="sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 